In [1]:
# Rank of a tensor 
# number of dimensions of the tensor 
import torch
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [3]:
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [2]:
# 3 rows and 3 cols
t.shape

torch.Size([3, 3])

In [4]:
# reshape the tensor into 1 row and 9 columns
t.reshape(1,9)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [5]:
# CNN tensor format 
# [batch size, color channel, height, width]

In [11]:
# reshaping operations
t1 = torch.Tensor([[1, 1, 1, 1],
                   [2, 2, 2, 2],
                   [3, 3, 3, 3],
                   [4, 4, 4, 4]
                   ])
print(t1.shape)
print(t1.numel())
print(t1.reshape(1,16))
print(t1.reshape(1,16).shape)
print(t1.reshape(1,16).squeeze())
print(t1.reshape(1,16).squeeze().shape)
print(t1.reshape(1,16).squeeze().unsqueeze(dim=0))
print(t1.reshape(1,16).squeeze().unsqueeze(dim=0).shape)

torch.Size([4, 4])
16
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]])
torch.Size([1, 16])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.])
torch.Size([16])
tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]])
torch.Size([1, 16])


In [12]:
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t 
print(flatten(t1))

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.])


In [13]:
# creating a batch 
t1 = torch.Tensor([[1, 1, 1, 1],
                   [1, 1, 1, 1],
                   [1, 1, 1, 1],
                   [1, 1, 1, 1]
                   ])
t2 = torch.Tensor([[2, 2, 2, 2],
                   [2, 2, 2, 2],
                   [2, 2, 2, 2],
                   [2, 2, 2, 2]
                   ])
t3 = torch.Tensor([[3, 3, 3, 3],
                   [3, 3, 3, 3],
                   [3, 3, 3, 3],
                   [3, 3, 3, 3]
                   ])

t = torch.stack((t1,t2,t3))
print(t)
print(t.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])
torch.Size([3, 4, 4])


In [16]:
# reshape into CNN tensor 
t = t.reshape(3,1,4,4)
print(t)
print(t.shape)
print("first item in the batch\n", t[0])
print('first color channel\n',t[0][0])
print('first row\n',t[0][0][0])
print('first column\n',t[0][0][0][0])

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.],
          [2., 2., 2., 2.]]],


        [[[3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.],
          [3., 3., 3., 3.]]]])
torch.Size([3, 1, 4, 4])
first item in the batch
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
first color channel
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row
 tensor([1., 1., 1., 1.])
first column
 tensor(1.)


In [17]:
# Element-wise operations 
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype = torch.float32)

t2 = torch.tensor([
    [1,1],
    [1,1]
], dtype = torch.float32)
print(t1 + t2)
print(t1 + 2)

tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])


In [18]:
# Reduction Operations 
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

print(t.sum(), t.sum().numel(), t.numel())
print(t.prod(), t.mean(), t.std())
print("sum of the cols\t", t.sum(dim=0))
print("sum of the rows\t", t.sum(dim=1))

tensor(8.) 1 9
tensor(0.) tensor(0.8889) tensor(1.1667)
sum of the rows	 tensor([2., 4., 2.])
sum of the cols	 tensor([1., 4., 3.])


In [27]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5],
],dtype=torch.float32)
print(t.max().item())
# max value from each columns
print(t.max(dim=0))
# return the rows that contain the max value from each columns 
print(t.argmax(dim=0))
# max value from each rows
print(t.max(dim=1).values.tolist())
# return the columns that contain the max value from each rows 
print(t.argmax(dim=1).tolist())

5.0
torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))
tensor([2, 1, 1, 2])
[2.0, 3.0, 5.0]
[3, 1, 3]
